// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iostrovok/conveyor/faces (interfaces: IHandler)

// Package mmock is a generated GoMock package.
package mmock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	faces "github.com/iostrovok/conveyor/faces"
	reflect "reflect"
	time "time"
)

// MockIHandler is a mock of IHandler interface
type MockIHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIHandlerMockRecorder
}

// MockIHandlerMockRecorder is the mock recorder for MockIHandler
type MockIHandlerMockRecorder struct {
	mock *MockIHandler
}

// NewMockIHandler creates a new mock instance
func NewMockIHandler(ctrl *gomock.Controller) *MockIHandler {
	mock := &MockIHandler{ctrl: ctrl}
	mock.recorder = &MockIHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIHandler) EXPECT() *MockIHandlerMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockIHandler) Run(arg0 faces.IItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockIHandlerMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIHandler)(nil).Run), arg0)
}

// Start mocks base method
func (m *MockIHandler) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockIHandlerMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIHandler)(nil).Start), arg0)
}

// Stop mocks base method
func (m *MockIHandler) Stop(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", arg0)
}

// Stop indicates an expected call of Stop
func (mr *MockIHandlerMockRecorder) Stop(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIHandler)(nil).Stop), arg0)
}

// TickerDuration mocks base method
func (m *MockIHandler) TickerDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TickerDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TickerDuration indicates an expected call of TickerDuration
func (mr *MockIHandlerMockRecorder) TickerDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TickerDuration", reflect.TypeOf((*MockIHandler)(nil).TickerDuration))
}

// TickerRun mocks base method
func (m *MockIHandler) TickerRun(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TickerRun", arg0)
}

// TickerRun indicates an expected call of TickerRun
func (mr *MockIHandlerMockRecorder) TickerRun(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TickerRun", reflect.TypeOf((*MockIHandler)(nil).TickerRun), arg0)
}
