// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iostrovok/conveyor/faces (interfaces: IItem)

// Package mmock is a generated GoMock package.
package mmock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	faces "github.com/iostrovok/conveyor/faces"
	reflect "reflect"
)

// MockIItem is a mock of IItem interface
type MockIItem struct {
	ctrl     *gomock.Controller
	recorder *MockIItemMockRecorder
}

// MockIItemMockRecorder is the mock recorder for MockIItem
type MockIItemMockRecorder struct {
	mock *MockIItem
}

// NewMockIItem creates a new mock instance
func NewMockIItem(ctrl *gomock.Controller) *MockIItem {
	mock := &MockIItem{ctrl: ctrl}
	mock.recorder = &MockIItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIItem) EXPECT() *MockIItemMockRecorder {
	return m.recorder
}

// AddError mocks base method
func (m *MockIItem) AddError(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddError", arg0)
}

// AddError indicates an expected call of AddError
func (mr *MockIItemMockRecorder) AddError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddError", reflect.TypeOf((*MockIItem)(nil).AddError), arg0)
}

// Cancel mocks base method
func (m *MockIItem) Cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel")
}

// Cancel indicates an expected call of Cancel
func (mr *MockIItemMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockIItem)(nil).Cancel))
}

// CleanError mocks base method
func (m *MockIItem) CleanError() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanError")
}

// CleanError indicates an expected call of CleanError
func (mr *MockIItemMockRecorder) CleanError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanError", reflect.TypeOf((*MockIItem)(nil).CleanError))
}

// Finish mocks base method
func (m *MockIItem) Finish() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finish")
}

// Finish indicates an expected call of Finish
func (mr *MockIItemMockRecorder) Finish() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockIItem)(nil).Finish))
}

// Get mocks base method
func (m *MockIItem) Get() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockIItemMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIItem)(nil).Get))
}

// GetContext mocks base method
func (m *MockIItem) GetContext() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// GetContext indicates an expected call of GetContext
func (mr *MockIItemMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockIItem)(nil).GetContext))
}

// GetError mocks base method
func (m *MockIItem) GetError() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetError")
	ret0, _ := ret[0].(error)
	return ret0
}

// GetError indicates an expected call of GetError
func (mr *MockIItemMockRecorder) GetError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetError", reflect.TypeOf((*MockIItem)(nil).GetError))
}

// GetHandlerError mocks base method
func (m *MockIItem) GetHandlerError() faces.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandlerError")
	ret0, _ := ret[0].(faces.Name)
	return ret0
}

// GetHandlerError indicates an expected call of GetHandlerError
func (mr *MockIItemMockRecorder) GetHandlerError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandlerError", reflect.TypeOf((*MockIItem)(nil).GetHandlerError))
}

// GetID mocks base method
func (m *MockIItem) GetID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetID indicates an expected call of GetID
func (mr *MockIItemMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockIItem)(nil).GetID))
}

// GetLastHandler mocks base method
func (m *MockIItem) GetLastHandler() faces.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastHandler")
	ret0, _ := ret[0].(faces.Name)
	return ret0
}

// GetLastHandler indicates an expected call of GetLastHandler
func (mr *MockIItemMockRecorder) GetLastHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastHandler", reflect.TypeOf((*MockIItem)(nil).GetLastHandler))
}

// GetPriority mocks base method
func (m *MockIItem) GetPriority() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriority")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPriority indicates an expected call of GetPriority
func (mr *MockIItemMockRecorder) GetPriority() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriority", reflect.TypeOf((*MockIItem)(nil).GetPriority))
}

// GetSkipToName mocks base method
func (m *MockIItem) GetSkipToName() faces.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkipToName")
	ret0, _ := ret[0].(faces.Name)
	return ret0
}

// GetSkipToName indicates an expected call of GetSkipToName
func (mr *MockIItemMockRecorder) GetSkipToName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkipToName", reflect.TypeOf((*MockIItem)(nil).GetSkipToName))
}

// LogTrace mocks base method
func (m *MockIItem) LogTrace(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LogTrace", varargs...)
}

// LogTrace indicates an expected call of LogTrace
func (mr *MockIItemMockRecorder) LogTrace(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTrace", reflect.TypeOf((*MockIItem)(nil).LogTrace), varargs...)
}

// LogTraceFinishTime mocks base method
func (m *MockIItem) LogTraceFinishTime(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LogTraceFinishTime", varargs...)
}

// LogTraceFinishTime indicates an expected call of LogTraceFinishTime
func (mr *MockIItemMockRecorder) LogTraceFinishTime(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTraceFinishTime", reflect.TypeOf((*MockIItem)(nil).LogTraceFinishTime), varargs...)
}

// NeedToSkip mocks base method
func (m *MockIItem) NeedToSkip(arg0 faces.IWorker) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedToSkip", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NeedToSkip indicates an expected call of NeedToSkip
func (mr *MockIItemMockRecorder) NeedToSkip(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedToSkip", reflect.TypeOf((*MockIItem)(nil).NeedToSkip), arg0)
}

// Set mocks base method
func (m *MockIItem) Set(arg0 interface{}) faces.IItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0)
	ret0, _ := ret[0].(faces.IItem)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockIItemMockRecorder) Set(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIItem)(nil).Set), arg0)
}

// SetHandlerError mocks base method
func (m *MockIItem) SetHandlerError(arg0 faces.Name) faces.IItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHandlerError", arg0)
	ret0, _ := ret[0].(faces.IItem)
	return ret0
}

// SetHandlerError indicates an expected call of SetHandlerError
func (mr *MockIItemMockRecorder) SetHandlerError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHandlerError", reflect.TypeOf((*MockIItem)(nil).SetHandlerError), arg0)
}

// SetID mocks base method
func (m *MockIItem) SetID(arg0 int64) faces.IItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetID", arg0)
	ret0, _ := ret[0].(faces.IItem)
	return ret0
}

// SetID indicates an expected call of SetID
func (mr *MockIItemMockRecorder) SetID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockIItem)(nil).SetID), arg0)
}

// SetLastHandler mocks base method
func (m *MockIItem) SetLastHandler(arg0 faces.Name) faces.IItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastHandler", arg0)
	ret0, _ := ret[0].(faces.IItem)
	return ret0
}

// SetLastHandler indicates an expected call of SetLastHandler
func (mr *MockIItemMockRecorder) SetLastHandler(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastHandler", reflect.TypeOf((*MockIItem)(nil).SetLastHandler), arg0)
}

// SetPriority mocks base method
func (m *MockIItem) SetPriority(arg0 int) faces.IItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPriority", arg0)
	ret0, _ := ret[0].(faces.IItem)
	return ret0
}

// SetPriority indicates an expected call of SetPriority
func (mr *MockIItemMockRecorder) SetPriority(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPriority", reflect.TypeOf((*MockIItem)(nil).SetPriority), arg0)
}

// SetSkipToName mocks base method
func (m *MockIItem) SetSkipToName(arg0 faces.Name) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSkipToName", arg0)
}

// SetSkipToName indicates an expected call of SetSkipToName
func (mr *MockIItemMockRecorder) SetSkipToName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSkipToName", reflect.TypeOf((*MockIItem)(nil).SetSkipToName), arg0)
}

// Start mocks base method
func (m *MockIItem) Start() faces.IItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(faces.IItem)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockIItemMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIItem)(nil).Start))
}
